services:
  db:
    image: mysql:8.0
    container_name: task-db
    environment:
      MYSQL_DATABASE: task_manager
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: task-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/task_manager?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: task-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend